/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankUsernameRouteImport } from './routes/rank/$username'
import { Route as LangsUsernameRouteImport } from './routes/langs/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankUsernameRoute = RankUsernameRouteImport.update({
  id: '/rank/$username',
  path: '/rank/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LangsUsernameRoute = LangsUsernameRouteImport.update({
  id: '/langs/$username',
  path: '/langs/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/langs/$username': typeof LangsUsernameRoute
  '/rank/$username': typeof RankUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/langs/$username': typeof LangsUsernameRoute
  '/rank/$username': typeof RankUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/langs/$username': typeof LangsUsernameRoute
  '/rank/$username': typeof RankUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/langs/$username' | '/rank/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/langs/$username' | '/rank/$username'
  id: '__root__' | '/' | '/langs/$username' | '/rank/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangsUsernameRoute: typeof LangsUsernameRoute
  RankUsernameRoute: typeof RankUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank/$username': {
      id: '/rank/$username'
      path: '/rank/$username'
      fullPath: '/rank/$username'
      preLoaderRoute: typeof RankUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/langs/$username': {
      id: '/langs/$username'
      path: '/langs/$username'
      fullPath: '/langs/$username'
      preLoaderRoute: typeof LangsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangsUsernameRoute: LangsUsernameRoute,
  RankUsernameRoute: RankUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
